// patch_coverage_report.js
//
// Post-process a tiarmcov / c29cov HTML coverage report for use inside the
// CCStudio IDE (Theia-based) webview, while also remaining readable when
// opened in a regular external browser.
//
// Background:
//   The raw HTML report generated by tiarmcov / c29cov (both wrappers around
//   llvm-cov) is functional but unstyled for TI branding and has several
//   usability problems when displayed inside the CCStudio IDE's embedded
//   webview panel:
//
//   1. The "jump to first uncovered line" link uses an anchor hash fragment
//      (e.g. #L42).  In a normal browser this scrolls within the page, but
//      in the Theia webview the hash change causes the *outer* IDE window to
//      scroll, hiding the editor tabs and making the report hard to use.
//
//   2. The webview has no browser back button.  Source file pages have no way
//      to return to the summary index page once the user clicks into them.
//
//   3. The report header just says "Coverage Report" with no project metadata.
//
//   4. The llvm-cov default styling is plain and does not match TI branding.
//
//   5. The CCStudio IDE may be in dark mode, but the report renders in light
//      mode only.
//
// What this script does (applied to every HTML file in the report directory):
//   1. Injects a small JavaScript snippet that detects at runtime whether the
//      page is inside a Theia webview and whether dark mode is active.  It
//      adds CSS body classes ("ccstudio", "dark") accordingly so that CSS rules
//      can target each context separately.
//
//   2. Replaces the plain "Coverage Report" header with a TI-branded header
//      bar showing the project name, compiler version, coverage type, and
//      generation date.
//
//   3. Appends TI brand CSS to style.css, providing:
//        - Light mode: TI red (#CC0000) header, clean table styling
//        - Dark mode: VS Code dark theme colors (detected at runtime)
//        - CCStudio webview: subtle border instead of full red banner
//
//   4. On source file pages only:
//        - Wraps the "jump to first uncovered line" link in a span that is
//          hidden via CSS inside the webview (but visible in a browser).
//        - Inserts a "← Summary" back-navigation link in the sticky header
//          bar so the user can return to the index page.
//
//   5. Replaces the llvm-cov footer ("Generated by llvm-cov -- llvm version X")
//      with a TI-branded footer ("Generated by TI Arm Clang Code Coverage Tools"
//      or "Generated by TI C29 Clang Code Coverage Tools").
//
// Usage (via the CCS scripting engine run.sh / run.bat):
//   run.sh patch_coverage_report.js <report_dir>
//       [--project <name>]
//       [--compiler <version>]
//       [--coverage-type <type>]
//       [--toolchain <name>]
//       [--ti-css <path>]
//
//   --project       Project name shown in the header metadata bar (optional)
//   --compiler      Compiler display string, e.g. "TI Clang v4.0.4.LTS" (optional)
//   --coverage-type Description of collection mode, e.g. "Source Coverage + MC/DC" (optional)
//   --toolchain     Brand string for the report footer (default: "TI Arm Clang").
//                   Use "TI C29 Clang" for C29 / C2000 projects.
//   --ti-css        Path to the shared ti-brand.css file from the CCS installation.
//                   When provided, the file is read and used instead of the embedded
//                   fallback CSS. Resolve via ccs.settings.md + platform path to
//                   {ccs_install}/ccs/.../ai/styles/ti-brand.css.
//
// Idempotency:
//   The script checks for a sentinel element (<div class='ti-patched'>) before
//   modifying each file.  Re-running the script on an already-patched report
//   is safe and produces no duplicate changes.

"use strict";

var fs   = require("fs");
var path = require("path");

// =============================================================================
// Sentinel strings
// =============================================================================
//
// These strings are embedded in the HTML as idempotency markers so that
// re-running the script on an already-patched file is safe and does nothing.

// Inserted as an invisible <div> at the top of the body in patched files.
// If this string is present, the file has already been patched by this script.
var TI_PATCHED_SENTINEL = "ti-patched";

// CSS class name added to the "← Summary" back-navigation link.
// Also used as a sentinel: if this class is already in the file, the back
// link has already been added and should not be added again.
var BACK_LINK_SENTINEL = "cov-back-link";

// Regex to find the relative path prefix to the report root from a source page.
// Source file pages live in subdirectories (e.g. coverage/path/to/file.c.html)
// and reference the shared style.css with a relative href like "../../style.css".
// We capture the prefix (e.g. "../../") so we can construct the path to index.html.
// Example match:  href='../../style.css'  →  captured group: "../../"
// On Windows, tiarmcov/c29cov emits backslash separators (e.g. "..\..\style.css"),
// so the pattern accepts both '/' and '\' as the separator character.
var CSS_HREF_RE = /href='((?:\.\.[\/\\])+)style\.css'/;

// =============================================================================
// Runtime environment detection script (injected into every HTML page)
// =============================================================================
//
// This inline JavaScript block is injected into every HTML page.  It runs in
// the browser / webview when the page loads and adds CSS classes to <body>:
//
//   "ccstudio" — the page is loaded inside a Theia/CCStudio IDE webview.
//                Detected by checking whether window.parent !== window
//                (webviews are always inside an iframe).
//
//   "dark"     — a dark color theme is active.  Detection tries three methods
//                in priority order:
//                  1. data-vscode-theme-kind attribute — set by the Theia host
//                     on the <body> or <html> element; most reliable when present.
//                  2. --vscode-editor-background CSS variable — injected by the
//                     Theia host into the webview's CSS; we measure its luminance
//                     to decide if it is a dark color.
//                  3. prefers-color-scheme media query — OS-level dark mode
//                     preference; used as a last resort.
//
// The resulting body classes drive the CSS rules in TI_CSS below.  For example:
//   body.ccstudio .jump-to-uncovered { display: none; }  ← hide in webview
//   body.dark .ti-header { background-color: #252526; }  ← dark mode header
//
// The script is written as a single concatenated string to make injection into
// the HTML simple (no multiline string handling needed at the injection site).

var ENV_DETECT_SCRIPT = "\
<script>\
(function(){\
  var inWebview = (window.parent !== window);\
  if(!inWebview) return;\
  document.body.classList.add('ccstudio');\
  var dark = false;\
  var tk = document.body.getAttribute('data-vscode-theme-kind')\
        || document.documentElement.getAttribute('data-vscode-theme-kind');\
  if(tk) {\
    dark = (tk === 'vscode-dark' || tk === 'vscode-high-contrast');\
  } else {\
    var bg = getComputedStyle(document.documentElement)\
             .getPropertyValue('--vscode-editor-background');\
    if(bg && bg.trim()) {\
      var d = document.createElement('div');\
      d.style.color = bg.trim();\
      document.body.appendChild(d);\
      var c = getComputedStyle(d).color;\
      document.body.removeChild(d);\
      var m = c.match(/rgb\\((\\d+),\\s*(\\d+),\\s*(\\d+)\\)/);\
      if(m) {\
        var lum = (0.299*parseInt(m[1]) + 0.587*parseInt(m[2]) + 0.114*parseInt(m[3])) / 255;\
        dark = (lum < 0.5);\
      }\
    } else if(window.matchMedia) {\
      dark = window.matchMedia('(prefers-color-scheme: dark)').matches;\
    }\
  }\
  if(dark) document.body.classList.add('dark');\
})();\
</script>";

// =============================================================================
// TI brand CSS (appended to style.css)
// =============================================================================
//
// This CSS block is appended to the report's shared style.css file.
//
// Structure:
//   Light mode (default, no body class):  TI brand red #CC0000, white background
//   body.ccstudio:                        Subtle TI header inside the IDE webview
//                                         (avoids the full red banner which is
//                                         visually heavy inside the dark IDE chrome)
//   body.dark:                            VS Code dark theme colors for all elements
//   body.ccstudio.dark:                   Dark header inside the dark webview
//
// The CSS is designed to cascade: dark mode rules override light mode rules,
// and ccstudio rules override generic rules.

var TI_CSS = "\n\
/* ===== TI Brand - Light Mode (default / external browser) ===== */\n\
body {\n\
  font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;\n\
  margin: 0;\n\
  color: #1a1a1a;\n\
  background: #ffffff;\n\
}\n\
.ti-header {\n\
  background-color: #cc0000;\n\
  color: #ffffff;\n\
  padding: 16px 24px;\n\
  display: flex;\n\
  align-items: center;\n\
  gap: 16px;\n\
}\n\
.ti-header h2 {\n\
  margin: 0;\n\
  font-size: 1.4em;\n\
  font-weight: 600;\n\
}\n\
.ti-meta {\n\
  background-color: #f5f5f5;\n\
  border-bottom: 1px solid #dbdbdb;\n\
  padding: 10px 24px;\n\
  font-size: 0.85em;\n\
  color: #555;\n\
  display: flex;\n\
  flex-wrap: wrap;\n\
  gap: 8px 24px;\n\
}\n\
.ti-meta span { white-space: nowrap; }\n\
.ti-meta strong { color: #333; }\n\
.centered {\n\
  margin: 20px 24px;\n\
  border: 1px solid #dbdbdb;\n\
  border-radius: 6px;\n\
  overflow: hidden;\n\
}\n\
.column-entry-bold {\n\
  font-weight: 600;\n\
  text-align: left;\n\
  background-color: #f9f9f9;\n\
  padding: 10px 8px;\n\
  border-bottom: 2px solid #cc0000;\n\
}\n\
.light-row:hover { background-color: #f5f5f5; }\n\
.light-row-bold {\n\
  background: #f9f9f9;\n\
  border: 1px solid #dbdbdb;\n\
  border-left: none;\n\
  border-right: none;\n\
  font-weight: 600;\n\
}\n\
.column-entry-green { text-align: left; background-color: #d4edda; }\n\
.column-entry-green:hover, tr:hover .column-entry-green { background-color: #e8f5e9; }\n\
.column-entry-red { text-align: left; background-color: #fce4e4; }\n\
.column-entry-red:hover, tr:hover .column-entry-red { background-color: #fff0f0; }\n\
.column-entry-yellow { text-align: left; background-color: #fff8e1; }\n\
.column-entry-yellow:hover, tr:hover .column-entry-yellow { background-color: #fffde7; }\n\
.column-entry-gray { text-align: left; background-color: #fbfbfb; }\n\
.column-entry-gray:hover, tr:hover .column-entry-gray { background-color: #f0f0f0; }\n\
h5 {\n\
  padding: 12px 24px;\n\
  color: #999;\n\
  font-weight: normal;\n\
  font-size: 0.8em;\n\
}\n\
.source-name-title {\n\
  padding: 8px 16px;\n\
  border-bottom: 1px solid #dbdbdb;\n\
  background-color: #f5f5f5;\n\
  line-height: 35px;\n\
  font-weight: 600;\n\
}\n\
a.cov-back-link {\n\
  color: #cc0000 !important;\n\
  font-weight: 600;\n\
  text-decoration: none;\n\
}\n\
a.cov-back-link:hover { text-decoration: underline !important; }\n\
\n\
/* In CCStudio webview: use a subtle bottom-border header instead of the full\n\
   red banner.  The red banner looks great in a browser but is visually heavy\n\
   inside the dark IDE chrome. */\n\
body.ccstudio .ti-header {\n\
  background-color: #f5f5f5;\n\
  color: #333;\n\
  padding: 12px 24px;\n\
  border-bottom: 2px solid #cc0000;\n\
}\n\
body.ccstudio.dark .ti-header {\n\
  background-color: #252526;\n\
  color: #cccccc;\n\
  border-bottom: 2px solid #cc0000;\n\
}\n\
/* Hide jump-to-uncovered link in the webview.\n\
   Clicking it changes the URL hash fragment, which causes the Theia IDE\n\
   outer panel to scroll and hides the editor tab bar. */\n\
body.ccstudio .jump-to-uncovered { display: none; }\n\
\n\
/* ===== Dark Mode (body class added at runtime by the injected script) ===== */\n\
body.dark {\n\
  background: #1e1e1e;\n\
  color: #cccccc;\n\
}\n\
body.dark .ti-header {\n\
  background-color: #cc0000;\n\
}\n\
body.dark .ti-meta {\n\
  background-color: #252526;\n\
  border-bottom-color: #3c3c3c;\n\
  color: #999;\n\
}\n\
body.dark .ti-meta strong { color: #cccccc; }\n\
body.dark .centered {\n\
  border-color: #3c3c3c;\n\
}\n\
body.dark table {\n\
  border-collapse: collapse;\n\
}\n\
body.dark .column-entry-bold {\n\
  background-color: #2d2d2d;\n\
  color: #cccccc;\n\
  border-bottom: 2px solid #cc0000;\n\
}\n\
body.dark .light-row {\n\
  background: #1e1e1e;\n\
  border-color: #3c3c3c;\n\
}\n\
body.dark .light-row:hover { background-color: #2a2d2e; }\n\
body.dark .light-row-bold {\n\
  background: #252526;\n\
  border-color: #3c3c3c;\n\
}\n\
body.dark .light-row td,\n\
body.dark .light-row-bold td {\n\
  border-right-color: #3c3c3c;\n\
  border-left-color: #3c3c3c;\n\
}\n\
body.dark .light-row a,\n\
body.dark .light-row pre { color: #cccccc; }\n\
body.dark .light-row a:hover { color: #4fc1ff; }\n\
body.dark .column-entry-green {\n\
  background-color: #1e3a1e;\n\
  color: #73c991;\n\
}\n\
body.dark .column-entry-green:hover,\n\
body.dark tr:hover .column-entry-green { background-color: #264d26; }\n\
body.dark .column-entry-red {\n\
  background-color: #3a1e1e;\n\
  color: #f48771;\n\
}\n\
body.dark .column-entry-red:hover,\n\
body.dark tr:hover .column-entry-red { background-color: #4d2626; }\n\
body.dark .column-entry-yellow {\n\
  background-color: #3a3a1e;\n\
  color: #dcdcaa;\n\
}\n\
body.dark .column-entry-yellow:hover,\n\
body.dark tr:hover .column-entry-yellow { background-color: #4d4d26; }\n\
body.dark .column-entry-gray {\n\
  background-color: #252526;\n\
  color: #888;\n\
}\n\
body.dark .column-entry-gray:hover,\n\
body.dark tr:hover .column-entry-gray { background-color: #2d2d2d; }\n\
body.dark h5 { color: #666; }\n\
body.dark tr:hover { background-color: #2a2d2e; }\n\
body.dark th, body.dark td {\n\
  border-right-color: #3c3c3c;\n\
  border-left-color: #3c3c3c;\n\
}\n\
/* Source file pages - dark mode overrides for the annotated code view */\n\
body.dark .source-name-title {\n\
  background-color: #252526;\n\
  border-bottom-color: #3c3c3c;\n\
  color: #cccccc;\n\
}\n\
body.dark a.cov-back-link { color: #ff6b6b !important; }\n\
body.dark pre { color: #cccccc; }\n\
body.dark .red { background-color: #4d2626; }\n\
body.dark .cyan { background-color: #1e3a3a; }\n\
body.dark .line-number { color: #5a5a5a; }\n\
body.dark .covered-line { color: #4fc1ff; }\n\
body.dark .uncovered-line { color: #f48771; }\n\
body.dark .tooltip { background-color: #264f78; }\n\
body.dark .expansion-view { border-color: #3c3c3c; }\n\
body.dark tr:has(> td > a:target) > td.code > pre { background-color: #3a3a1e; }\n\
";

// =============================================================================
// Recursive HTML file finder
// =============================================================================
//
// Walks a directory tree and returns the paths of all .html files found.
// The coverage report tool generates a flat index.html plus a subdirectory
// tree of per-source-file HTML pages, so we need to recurse.

function findHtmlFiles(dir) {
    var results = [];
    var entries = fs.readdirSync(dir);

    for (var i = 0; i < entries.length; i++) {
        var fullPath = path.join(dir, entries[i]);
        var stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
            // Recurse into subdirectories to find nested source file pages
            var nested = findHtmlFiles(fullPath);
            for (var j = 0; j < nested.length; j++) {
                results.push(nested[j]);
            }
        } else if (entries[i].endsWith(".html")) {
            results.push(fullPath);
        }
    }

    return results;
}

// =============================================================================
// TI branded header HTML builder
// =============================================================================
//
// Builds the replacement header block that replaces the plain llvm-cov header.
// The header consists of two divs:
//   .ti-header  — the colored title bar ("Code Coverage Report")
//   .ti-meta    — a metadata strip below the title showing project, compiler,
//                 coverage type, and generation date
//
// The TI_PATCHED_SENTINEL div is the idempotency marker: its presence in the
// file means the header has already been replaced and should not be replaced again.

function buildHeader(dateStr, opts) {
    // Start with the invisible sentinel div and the title bar
    var header =
        "<div class='" + TI_PATCHED_SENTINEL + "'></div>" +
        "<div class='ti-header'>" +
        "<h2>Code Coverage Report</h2>" +
        "</div>" +
        "<div class='ti-meta'>";

    // Add each metadata field only if provided (all are optional)
    if (opts.projectName) {
        header += "<span><strong>Project:</strong> " + opts.projectName + "</span>";
    }
    if (opts.compilerVersion) {
        header += "<span><strong>Compiler:</strong> " + opts.compilerVersion + "</span>";
    }
    if (opts.coverageType) {
        header += "<span><strong>Coverage:</strong> " + opts.coverageType + "</span>";
    }

    // Generation date is always included (extracted from the original report header)
    header += "<span><strong>Generated:</strong> " + dateStr + "</span>";
    header += "</div>";

    return header;
}

// =============================================================================
// Patch index.html (the coverage summary page)
// =============================================================================
//
// The index page is the landing page showing overall coverage percentages for
// each source file.  It contains:
//   - The report title header (h2 + h4)
//   - A table of per-file coverage statistics
//   - A footer with the llvm-cov version string
//
// We make three changes:
//   1. Inject the environment detection script before </body>
//   2. Replace the plain h2/h4/p header with the TI branded header
//   3. Replace the llvm-cov footer with a TI-branded footer
//
// Returns true if the file was modified, false if it was already patched.

function patchIndexPage(filePath, opts) {
    var content = fs.readFileSync(filePath, "utf-8");
    var original = content;

    // Idempotency check: if the sentinel is already present, skip this file
    if (content.indexOf(TI_PATCHED_SENTINEL) !== -1) {
        return false;
    }

    // 1. Inject the runtime environment detection script.
    //    Placing it before </body> ensures it runs after the DOM is loaded.
    content = content.replace("</body>", ENV_DETECT_SCRIPT + "</body>");

    // 2. Replace the plain llvm-cov header block with the TI branded header.
    //    The original header looks like:
    //      <h2>Coverage Report</h2>
    //      <h4>Created: Mon Jan 1 00:00:00 2025</h4>
    //      <p>Click <a ...>here</a> for information about interpreting this report.</p>
    //    We capture the date string from the h4 so we can include it in the new header.
    content = content.replace(
        /<h2>Coverage Report<\/h2><h4>Created: ([^<]+)<\/h4><p>Click <a[^>]*>[^<]*<\/a> for information about interpreting this report\.<\/p>/,
        function(match, dateStr) {
            return buildHeader(dateStr, opts);
        }
    );

    // 3. Replace the llvm-cov footer.
    //    The original footer looks like:
    //      <h5>Generated by llvm-cov -- llvm version 17.0.0</h5>
    //    We replace it with a TI-branded equivalent that names the actual tool used.
    //    The toolchain name ("TI Arm Clang" or "TI C29 Clang") comes from the
    //    --toolchain command-line argument.
    content = content.replace(
        /<h5>Generated by llvm-cov -- llvm version [^<]*<\/h5>/,
        "<h5>Generated by " + opts.toolchain + " Code Coverage Tools</h5>"
    );

    // If nothing changed (header pattern didn't match), report was in an unexpected
    // format — return false to skip writing
    if (content === original) {
        return false;
    }

    fs.writeFileSync(filePath, content, "utf-8");
    return true;
}

// =============================================================================
// Patch source file pages
// =============================================================================
//
// Source file pages show the annotated source code with line-level coverage
// highlighting.  They contain:
//   - The same h2/h4 header as index.html
//   - A sticky "source-name-title" bar showing the file path
//   - The "jump to first uncovered line" link (problematic in webview)
//   - The annotated source code
//
// We make four changes (in addition to the same header/footer replacements):
//   1. Inject the environment detection script (same as index page)
//   2. Replace the h2/h4 header with the TI branded header
//   3. Wrap the "jump to first uncovered line" link so it can be hidden via CSS
//   4. Insert a "← Summary" back-navigation link in the sticky header bar
//
// Returns true if the file was modified, false otherwise.

function patchSourceFile(filePath, opts) {
    var content = fs.readFileSync(filePath, "utf-8");
    var original = content;

    // 1. Inject the runtime environment detection script.
    //    Guard against double-injection: if "ccstudio" class is already in the
    //    file, the script was already injected on a previous run.
    if (content.indexOf("ccstudio") === -1) {
        content = content.replace("</body>", ENV_DETECT_SCRIPT + "</body>");
    }

    // 2. Replace the h2/h4 header with the TI branded header.
    //    Source pages have the same header format as the index page but without
    //    the "Click here for information..." paragraph.
    //    Guard with sentinel check to avoid double-replacement on re-runs.
    if (content.indexOf(TI_PATCHED_SENTINEL) === -1) {
        content = content.replace(
            /<h2>Coverage Report<\/h2><h4>Created: ([^<]+)<\/h4>/,
            function(match, dateStr) {
                return buildHeader(dateStr, opts);
            }
        );
    }

    // 3. Wrap the "jump to first uncovered line" link in a <span> for CSS hiding.
    //    The link text is "jump to first uncovered line" and it is surrounded by
    //    parentheses.  When clicked inside the CCStudio webview it changes the URL
    //    hash, which Theia interprets as a navigation event and scrolls the outer
    //    IDE window — hiding the editor tab bar.  We hide it only in the webview
    //    using: body.ccstudio .jump-to-uncovered { display: none; }
    //    In an external browser the link remains fully visible and functional.
    content = content.replace(
        /(\s*\(<a[^>]*>jump to first uncovered line<\/a>\))/g,
        "<span class='jump-to-uncovered'>$1</span>"
    );

    // 4. Insert a "← Summary" back-navigation link in the sticky source-name header.
    //    The Theia webview has no browser history or back button.  Without this link,
    //    once the user clicks into a source file page from the index there is no way
    //    to return to the summary index page.
    //
    //    We locate the index.html path by extracting the relative path prefix from
    //    the style.css href (e.g. "../../" if this file is two levels deep), then
    //    construct the back link as "../../index.html".
    //
    //    Guard against double-insertion using BACK_LINK_SENTINEL.
    if (content.indexOf(BACK_LINK_SENTINEL) === -1) {
        var m = CSS_HREF_RE.exec(content);
        if (m) {
            // m[1] is the relative prefix, e.g. "../../" (or "..\..\" on Windows).
            // Normalize to forward slashes since this is an HTML href (URL).
            var prefix    = m[1].replace(/\\/g, '/');
            var indexHref = prefix + "index.html";

            // Build the anchor element with inline style to match the header bar
            var backLink =
                "<a class='" + BACK_LINK_SENTINEL + "' href='" + indexHref +
                "' style='margin-right:12px;text-decoration:none;" +
                "font-size:0.9em'>&#8592; Summary</a>";

            // Insert the link at the very start of the sticky header div content,
            // before the filename text
            content = content.replace(
                "<div class='source-name-title'>",
                "<div class='source-name-title'>" + backLink
            );
        }
    }

    // If nothing changed, return false to avoid an unnecessary file write
    if (content === original) {
        return false;
    }

    fs.writeFileSync(filePath, content, "utf-8");
    return true;
}

// =============================================================================
// Patch the shared stylesheet
// =============================================================================
//
// The coverage report uses a single style.css shared by all pages.  We append
// the TI brand CSS block to it.  Appending (rather than replacing) means the
// TI rules have higher specificity and override the default llvm-cov styles
// only where we explicitly define them, leaving everything else intact.
//
// Guards against double-patching by checking for the "TI Brand" comment string.

function patchStylesheet(reportDir, tiCssPath) {
    var cssPath = path.join(reportDir, "style.css");
    try {
        var content = fs.readFileSync(cssPath, "utf-8");

        // Idempotency check: the TI_CSS block starts with a "TI Brand" comment
        if (content.indexOf("TI Brand") !== -1) {
            return false; // already patched
        }

        // Use the shared ti-brand.css if a path was provided and the file is readable;
        // otherwise fall back to the embedded TI_CSS constant.
        var brandCss = TI_CSS;
        if (tiCssPath) {
            try {
                brandCss = fs.readFileSync(tiCssPath, "utf-8");
            } catch (e) {
                console.warn("Warning: could not read --ti-css '" + tiCssPath + "', using built-in fallback.");
            }
        }

        // Append the TI CSS to the existing stylesheet
        fs.writeFileSync(cssPath, content + brandCss, "utf-8");
        return true;
    } catch (e) {
        // style.css may not exist in some edge cases — log and continue
        return false;
    }
}

// =============================================================================
// Argument parsing
// =============================================================================
//
// This script is invoked via the CCS scripting engine (run.sh / run.bat) which
// prepends two arguments: the Node.js executable path and the script path.
// process.argv therefore looks like:
//   ["/path/to/node", "/path/to/patch_coverage_report.js", arg1, arg2, ...]
// so we slice from index 3 (not 2) to get the user-supplied arguments.

var args = process.argv.slice(3);
var reportDir       = null;
var projectName     = null;
var compilerVersion = null;
var coverageType    = null;
var toolchain       = "TI Arm Clang"; // default; override with --toolchain for C29
var tiCssPath       = null;            // path to shared ti-brand.css; falls back to TI_CSS

for (var i = 0; i < args.length; i++) {
    if (args[i] === "--project" && i + 1 < args.length) {
        // Project name shown in the metadata bar of the report header
        projectName = args[++i];
    } else if (args[i] === "--compiler" && i + 1 < args.length) {
        // Compiler display string, e.g. "TI Clang v4.0.4.LTS" or "TI Clang v2.0.0.STS"
        compilerVersion = args[++i];
    } else if (args[i] === "--coverage-type" && i + 1 < args.length) {
        // Human-readable description of which flags were active, e.g.:
        //   "Source Coverage"               (default, -fprofile-instr-generate only)
        //   "Function Coverage"             (-ffunction-coverage-only)
        //   "Source Coverage + MC/DC"       (-fmcdc)
        coverageType = args[++i];
    } else if (args[i] === "--toolchain" && i + 1 < args.length) {
        // Brand name for the report footer.  Use "TI Arm Clang" for Arm projects
        // (TMS470 compiler family) or "TI C29 Clang" for C29 / C2000 projects.
        toolchain = args[++i];
    } else if (args[i] === "--ti-css" && i + 1 < args.length) {
        // Path to the shared ti-brand.css from the CCS installation.
        // If readable, its content is used instead of the embedded TI_CSS fallback.
        tiCssPath = args[++i];
    } else if (!reportDir) {
        // First positional argument is the report directory to patch
        reportDir = args[i];
    }
}

// Validate that a report directory was provided
if (!reportDir) {
    console.error(
        "Usage: run.sh patch_coverage_report.js <report_dir> " +
        "[--project <name>] [--compiler <version>] [--coverage-type <type>] " +
        "[--toolchain <name>]"
    );
    process.exit(1);
}

// Verify the path is an actual directory (not a file or missing path)
try {
    var st = fs.statSync(reportDir);
    if (!st.isDirectory()) {
        throw new Error("not a directory");
    }
} catch (e) {
    console.error("Error: '" + reportDir + "' is not a directory");
    process.exit(1);
}

// =============================================================================
// Main patching sequence
// =============================================================================

// Bundle all the metadata options into a single object for easy passing around
var opts = {
    projectName:     projectName,
    compilerVersion: compilerVersion,
    coverageType:    coverageType,
    toolchain:       toolchain,
};

// Step 1: Patch the shared stylesheet first so styles are ready when the
//         browser loads the HTML.  This must run before the HTML pages so
//         that the first load already has correct styling.
if (patchStylesheet(reportDir, tiCssPath)) {
    console.log("  Patched: style.css");
}

// Step 2: Patch the summary index page
var indexPath = path.join(reportDir, "index.html");
try {
    if (patchIndexPage(indexPath, opts)) {
        console.log("  Patched: index.html");
    }
} catch (e) {
    // Non-fatal: log the warning and continue patching the source pages
    console.error("Warning: could not patch index.html: " + e.message);
}

// Step 3: Patch all source file pages
//         findHtmlFiles recursively collects every .html file in the report
//         directory tree, then we skip index.html (already patched above).
var htmlFiles = findHtmlFiles(reportDir);
var patched = 0;

for (var j = 0; j < htmlFiles.length; j++) {
    // Skip index.html — it was handled separately above
    if (htmlFiles[j] === indexPath) {
        continue;
    }

    if (patchSourceFile(htmlFiles[j], opts)) {
        // Print the path relative to the report root for readability
        console.log("  Patched: " + path.relative(reportDir, htmlFiles[j]));
        patched++;
    }
}

// Print a final summary.  +2 accounts for style.css and index.html which are
// not counted in the 'patched' source-file counter.
console.log("\n" + (patched + 2) + " file(s) patched in '" + reportDir + "'");
